// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DetalhesEvento: typeof import('./src/components/eventos/DetalhesEvento.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EventoComponent: typeof import('./src/components/eventos/EventoComponent.vue')['default']
    EventoLista: typeof import('./src/components/eventos/EventoLista.vue')['default']
    FormularioEvento: typeof import('./src/components/eventos/FormularioEvento.vue')['default']
    LoginComponent: typeof import('./src/components/user/login/LoginComponent.vue')['default']
    LotesEvento: typeof import('./src/components/eventos/LotesEvento.vue')['default']
    PalestrantesComponent: typeof import('./src/components/palestrantes/PalestrantesComponent.vue')['default']
    RegistrarUsuario: typeof import('./src/components/user/registrar/RegistrarUsuario.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserComponent: typeof import('./src/components/user/UserComponent.vue')['default']
  }
}
